// Lista de estações (réplica de estacoes.h do ESP32)
const ESTACOES = [
  { id: 1, nome: "E - Lonas" },
  { id: 2, nome: "P - Tekas" },
  { id: 3, nome: "W - Acabamentos Montagem" },
  { id: 4, nome: "K - TopCoat" },
  { id: 5, nome: "A - Teste D'Água" },
  { id: 6, nome: "W - CNC - LECTRA" },
  { id: 7, nome: "H - Preparação" },
  { id: 8, nome: "H - Lam 1" },
  { id: 9, nome: "A - Sikas" },
  { id: 10, nome: "A - Auditoria Gate 5" },
  { id: 11, nome: "T - Medium Parts" },
  { id: 12, nome: "K - Liner/Banheira" },
  { id: 13, nome: "E - CNC" },
  { id: 14, nome: "W - CNC - MORBIDELLI" },
  { id: 15, nome: "A - União" },
  { id: 16, nome: "A - Open Hull 01" },
  { id: 17, nome: "D - Open Deck 01" },
  { id: 18, nome: "C - Reparação" },
  { id: 19, nome: "P - Marcação" },
  { id: 20, nome: "H - Skiin" },
  { id: 21, nome: "H - Cabine de Pintura" },
  { id: 22, nome: "C - Teste D'Água" },
  { id: 23, nome: "C - Final" },
  { id: 24, nome: "N - Empaste" },
  { id: 25, nome: "K - POP" },
  { id: 26, nome: "A - Open Hull" },
  { id: 27, nome: "M - Repassagem" },
  { id: 28, nome: "D - Sikas" },
  { id: 29, nome: "S - Sikas" },
  { id: 30, nome: "T - Coberta" },
  { id: 31, nome: "A - Final" },
  { id: 32, nome: "K - Estruturas" },
  { id: 33, nome: "D - Open Hull 02" },
  { id: 34, nome: "T - Small Parts" },
  { id: 35, nome: "E - Montagem Estofos" },
  { id: 36, nome: "H - Repassagem" },
  { id: 37, nome: "A - Auditoria Gate 6" },
  { id: 38, nome: "& - Empaste Big Parts" },
  { id: 39, nome: "H - Stiffen" },
  { id: 40, nome: "S - Repassagem" },
  { id: 41, nome: "D - Teste D'Água" },
  { id: 42, nome: "B - Reparação" },
  { id: 43, nome: "H - Lam 2" },
  { id: 44, nome: "C - União" },
  { id: 45, nome: "M - Stiffen" },
  { id: 46, nome: "H - POP" },
  { id: 47, nome: "A - Embalamento" },
  { id: 48, nome: "P - Tampas" },
  { id: 49, nome: "S - Costura" },
  { id: 50, nome: "E - Bancos" },
  { id: 51, nome: "D - Auditoria Gate 5" },
  { id: 52, nome: "H - União Liner" },
  { id: 53, nome: "N - Reparação" },
  { id: 54, nome: "B - Open Hull" },
  { id: 55, nome: "D - Auditoria Gate 6" },
  { id: 56, nome: "P - Móveis/Bancos" },
  { id: 57, nome: "S - Tanques" },
  { id: 58, nome: "K - Marcação" },
  { id: 59, nome: "C - Embalamento" },
  { id: 60, nome: "H - Trampson/Espumas" },
  { id: 61, nome: "B - Sikas" },
  { id: 62, nome: "N - Ceras" },
  { id: 63, nome: "Rework" },
  { id: 64, nome: "C - Embalamento" },
  { id: 65, nome: "B - Open Deck" },
  { id: 66, nome: "M - Madeiras" },
  { id: 67, nome: "M - Cabine de Pintura" },
  { id: 68, nome: "W - Pick Assy/PM" },
  { id: 69, nome: "M - Preparação" },
  { id: 70, nome: "P - Topcoat" },
  { id: 71, nome: "B - Estruturas" },
  { id: 72, nome: "S - Final" },
  { id: 73, nome: "W - Madeiras Laminação" },
  { id: 74, nome: "S - Cabine de Pintura" },
  { id: 75, nome: "M - Skin" },
  { id: 76, nome: "K - Skin" },
  { id: 77, nome: "S - Skin" },
  { id: 78, nome: "A - Teste D'água" },
  { id: 79, nome: "& - Reparação Laminação" },
  { id: 80, nome: "D - Stiffen" },
  { id: 81, nome: "D - Open Deck 02" },
  { id: 82, nome: "B - Auditoria Gate 5" },
  { id: 83, nome: "M - Estrutura" },
  { id: 84, nome: "S - Preparação" },
  { id: 85, nome: "& - Empaste Small Parts" },
  { id: 86, nome: "E - Pick" },
  { id: 87, nome: "W - Espumas Laminação" },
  { id: 88, nome: "C - Open Deck" },
  { id: 89, nome: "M - TopCoat" },
  { id: 90, nome: "S - POP" },
  { id: 91, nome: "& - Reparação Big Parts" },
  { id: 92, nome: "M - POP" },
  { id: 93, nome: "C - Open Hull" },
  { id: 94, nome: "D - Final" },
  { id: 95, nome: "C - Auditoria Gate 5" },
  { id: 96, nome: "S - Colagem" },
  { id: 97, nome: "C - Auditoria Gate 6" },
  { id: 98, nome: "W - CNC - FANUC" },
  { id: 99, nome: "D - Reparação" },
  { id: 100, nome: "E - Tapizados" },
  { id: 101, nome: "K - Cabine de Pintura" },
  { id: 102, nome: "A - Open Deck" },
  { id: 103, nome: "P - Liners/Hardtop" },
  { id: 104, nome: "K - Repassagem" },
  { id: 105, nome: "T - Casco" },
  { id: 106, nome: "B - Embalamento" },
  { id: 107, nome: "K - Stiffen" },
  { id: 108, nome: "B - União" },
  { id: 109, nome: "K - Preparação" },
  { id: 110, nome: "& - Reparação Small Parts" },
  { id: 111, nome: "D - União" },
  { id: 112, nome: "A - Consola/Módulos" },
  { id: 113, nome: "P - MORBIDELLI" },
  { id: 114, nome: "T - BottomPaint" },
  { id: 115, nome: "A - Reparação" },
];

function procurarEstacao(id) {
  const e = ESTACOES.find((e) => e.id === id);
  return e ? e.nome : "NAO_ENCONTRADA";
}

function procurarEstacaoPorNome(nome) {
  const e = ESTACOES.find((e) => e.nome === nome);
  return e ? e.id : -1;
}

function procurarIndiceEstacao(nome) {
  const idx = ESTACOES.findIndex((e) => e.nome === nome);
  return idx >= 0 ? idx : 0;
}
